export const queryKeys = {
  user: {
    all: ['user'] as const,
    profile: () => [...queryKeys.user.all, 'profile'] as const,
    leagues: () => [...queryKeys.user.all, 'leagues'] as const,
    dashboardSummary: () => [...queryKeys.user.all, 'dashboard-summary'] as const,
    payments: () => [...queryKeys.user.all, 'payments'] as const,
    rejectedSubmissions: () => [...queryKeys.user.all, 'rejected-submissions'] as const,
  },
  leagues: {
    all: ['leagues'] as const,
    detail: (id: string) => [...queryKeys.leagues.all, id] as const,
    members: (id: string) => [...queryKeys.leagues.all, id, 'members'] as const,
    leaderboard: (id: string, params?: Record<string, string>) => [...queryKeys.leagues.all, id, 'leaderboard', params] as const,
    activities: (id: string) => [...queryKeys.leagues.all, id, 'activities'] as const,
    activityMinimums: (id: string) => [...queryKeys.leagues.all, id, 'activity-minimums'] as const,
    dashboardSummary: (id: string) => [...queryKeys.leagues.all, id, 'dashboard-summary'] as const,
    mySubmissions: (id: string) => [...queryKeys.leagues.all, id, 'my-submissions'] as const,
    teams: (id: string) => [...queryKeys.leagues.all, id, 'teams'] as const,
    teamMembers: (id: string, teamId: string) => [...queryKeys.leagues.all, id, 'teams', teamId, 'members'] as const,
    roles: (id: string) => [...queryKeys.leagues.all, id, 'roles'] as const,
    challenges: (id: string) => [...queryKeys.leagues.all, id, 'challenges'] as const,
    challengeDetail: (id: string, cid: string) => [...queryKeys.leagues.all, id, 'challenges', cid] as const,
    messages: (id: string) => [...queryKeys.leagues.all, id, 'messages'] as const,
    unreadCount: (id: string) => [...queryKeys.leagues.all, id, 'messages', 'unread-count'] as const,
    restDays: (id: string) => [...queryKeys.leagues.all, id, 'rest-days'] as const,
    restDayDonations: (id: string) => [...queryKeys.leagues.all, id, 'rest-day-donations'] as const,
    rules: (id: string) => [...queryKeys.leagues.all, id, 'rules'] as const,
    analytics: (id: string) => [...queryKeys.leagues.all, id, 'analytics'] as const,
    aiCoach: (id: string) => [...queryKeys.leagues.all, id, 'ai-coach'] as const,
    aiCoachHistory: (id: string) => [...queryKeys.leagues.all, id, 'ai-coach', 'history'] as const,
    aiCoachSuggestions: (id: string) => [...queryKeys.leagues.all, id, 'ai-coach', 'suggestions'] as const,
    aiCoachMilestones: (id: string) => [...queryKeys.leagues.all, id, 'ai-coach', 'milestones'] as const,
    aiCoachRecovery: (id: string) => [...queryKeys.leagues.all, id, 'ai-coach', 'recovery'] as const,
    aiCoachWeeklyInsight: (id: string) => [...queryKeys.leagues.all, id, 'ai-coach', 'weekly-insight'] as const,
    aiUsage: (id: string, days?: number) => [...queryKeys.leagues.all, id, 'ai-usage', days] as const,
    governor: (id: string) => [...queryKeys.leagues.all, id, 'governor'] as const,
    submissions: (id: string) => [...queryKeys.leagues.all, id, 'submissions'] as const,
    teamSubmissions: (id: string) => [...queryKeys.leagues.all, id, 'team-submissions'] as const,
    partnerActivity: (id: string, teamId?: string) => [...queryKeys.leagues.all, id, 'partner-activity', teamId] as const,
    teamView: (id: string, teamId: string) => [...queryKeys.leagues.all, id, 'team-view', teamId] as const,
    teamSummary: (id: string) => [...queryKeys.leagues.all, id, 'my-team-summary'] as const,
    sponsors: (id: string) => [...queryKeys.leagues.all, id, 'sponsors'] as const,
    wearableConnections: (id: string) => [...queryKeys.leagues.all, id, 'wearable-connections'] as const,
    pendingConfirmations: (id: string) => [...queryKeys.leagues.all, id, 'pending-confirmations'] as const,
  },
  dashboard: {
    all: ['dashboard'] as const,
    leagues: () => [...queryKeys.dashboard.all, 'leagues'] as const,
  },
  entries: {
    all: ['entries'] as const,
    mySubmissions: (leagueId: string) => [...queryKeys.entries.all, 'my-submissions', leagueId] as const,
    previewRR: () => [...queryKeys.entries.all, 'preview-rr'] as const,
  },
  customActivities: {
    all: ['custom-activities'] as const,
  },
  tiers: {
    all: ['tiers'] as const,
    previewPrice: (params?: Record<string, string>) => [...queryKeys.tiers.all, 'preview-price', params] as const,
  },
  notifications: {
    all: ['notifications'] as const,
  },
  invites: {
    validate: (code: string) => ['invites', code] as const,
    validateTeam: (code: string) => ['invites', 'team', code] as const,
  },
} as const;
